"""
Pydantic models for investment thesis and strategy recommendations.
"""
from pydantic import BaseModel, Field
from typing import List, Optional, Literal


class InvestmentThesis(BaseModel):
    """Structured investment thesis generated by AI."""

    direction: Literal["BULLISH", "BEARISH", "NEUTRAL", "UNPREDICTABLE"] = Field(
        description="Overall market direction expectation"
    )

    conviction: int = Field(
        ge=0, le=100,
        description="Conviction level from 0-100%"
    )

    expected_move: str = Field(
        description="Expected price move (e.g., '+15% in 45 days')"
    )

    expected_move_pct: float = Field(
        description="Expected move as percentage (e.g., 15.0 for +15%)"
    )

    target_price: float = Field(
        description="Target stock price"
    )

    timeframe: str = Field(
        description="Timeframe for thesis (e.g., '30-45 days')"
    )

    timeframe_days: int = Field(
        description="Timeframe in days (e.g., 45)"
    )

    thesis_summary: str = Field(
        description="2-3 sentence summary of the investment thesis"
    )

    research_insights: str = Field(
        default="",
        description="Detailed summary of key research findings (5-10 sentences explaining what research revealed and how it informed the thesis)"
    )

    bull_case: List[str] = Field(
        description="List of bullish factors with specific data points"
    )

    bear_case: List[str] = Field(
        description="List of bearish risks with specific concerns"
    )

    catalysts: List[str] = Field(
        default_factory=list,
        description="Upcoming catalysts or events"
    )

    key_risks: List[str] = Field(
        default_factory=list,
        description="Key risks that could invalidate thesis"
    )

    data_references: dict = Field(
        default_factory=dict,
        description="Specific data points used in analysis"
    )


class ContractSelection(BaseModel):
    """Specific options contract selected by the bot."""

    action: Literal["BUY", "SELL"] = Field(
        description="Whether to buy or sell this contract"
    )

    symbol: str = Field(
        description="Full contract symbol (e.g., 'NVDA250321C00140000')"
    )

    display_name: str = Field(
        description="Human-readable name (e.g., 'NVDA Mar21 $140 Call')"
    )

    strike: float = Field(
        description="Strike price"
    )

    expiration: str = Field(
        description="Expiration date (YYYY-MM-DD)"
    )

    option_type: Literal["call", "put"] = Field(
        description="Call or put"
    )

    premium: float = Field(
        description="Option premium (mid of bid/ask)"
    )

    delta: float = Field(
        description="Delta (0-1 for calls, 0 to -1 for puts)"
    )

    quantity: int = Field(
        default=1,
        description="Number of contracts"
    )

    cost_or_credit: float = Field(
        description="Total cost (if BUY) or credit (if SELL) in dollars"
    )


class StrategyRecommendation(BaseModel):
    """Complete options strategy recommendation."""

    strategy: str = Field(
        description="Name of the strategy (e.g., 'Bull Call Spread')"
    )

    strategy_type: Literal["Debit Spread", "Credit Spread", "Directional", "Neutral", "Income"] = Field(
        description="Category of strategy"
    )

    rationale: str = Field(
        description="Why this strategy fits the thesis (2-3 sentences)"
    )

    research_summary: str = Field(
        default="",
        description="Summary of research findings that led to this strategy choice (3-5 sentences)"
    )

    how_it_works: str = Field(
        description="Plain English explanation of how the strategy works (5-8 sentences, explain like user knows nothing about options)"
    )

    price_movements: str = Field(
        description="What price movements this strategy profits from"
    )

    contracts: List[ContractSelection] = Field(
        description="Specific contracts to trade"
    )

    net_debit_credit: float = Field(
        description="Net debit paid (positive) or credit received (negative)"
    )

    max_profit: float = Field(
        description="Maximum potential profit"
    )

    max_loss: float = Field(
        description="Maximum potential loss"
    )

    breakeven: float = Field(
        description="Breakeven stock price"
    )

    risk_reward_ratio: float = Field(
        description="Max profit / Max loss ratio"
    )

    stock_requirement: str = Field(
        description="Whether stock position is required (e.g., 'Must own 100 shares')"
    )

    probability_of_profit: Optional[float] = Field(
        None,
        description="Estimated probability of profit (0-1)"
    )


class CompleteAnalysis(BaseModel):
    """Complete analysis output combining thesis and strategy."""

    ticker: str = Field(
        description="Stock ticker analyzed"
    )

    current_price: float = Field(
        description="Current stock price"
    )

    analysis_date: str = Field(
        description="Date of analysis (YYYY-MM-DD)"
    )

    thesis: InvestmentThesis = Field(
        description="Investment thesis"
    )

    strategy: StrategyRecommendation = Field(
        description="Recommended options strategy"
    )
